version: '3.8'
services:
  gateway_api:
    build: .
    command: 'dotnet Inplanticular.ApiGateway.dll --urls=http://*:7005 --environment="Development"'
    restart: unless-stopped
    ports:
      - 7005:7005
    networks:
      - inplanticular_net

networks:
  inplanticular_net:
    name: inplanticular_net
    driver: bridge